# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JN\source\repos\部落格範例\部落格範例\matplotlib繪圖互動2\mlt2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 500)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(122, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.lines = QtWidgets.QListWidget(self.groupBox)
        self.lines.setGeometry(QtCore.QRect(0, 20, 121, 231))
        self.lines.setObjectName("lines")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 300, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.aV = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.aV.setGeometry(QtCore.QRect(40, 320, 62, 22))
        self.aV.setMinimum(-99.99)
        self.aV.setObjectName("aV")
        self.bV = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.bV.setGeometry(QtCore.QRect(40, 350, 62, 22))
        self.bV.setMinimum(-99.99)
        self.bV.setObjectName("bV")
        self.cV = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.cV.setGeometry(QtCore.QRect(40, 380, 62, 22))
        self.cV.setMinimum(-99.99)
        self.cV.setObjectName("cV")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 380, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_add = QtWidgets.QPushButton(self.groupBox)
        self.btn_add.setGeometry(QtCore.QRect(10, 260, 41, 23))
        self.btn_add.setObjectName("btn_add")
        self.btn_del = QtWidgets.QPushButton(self.groupBox)
        self.btn_del.setGeometry(QtCore.QRect(70, 260, 41, 23))
        self.btn_del.setObjectName("btn_del")
        self.legned = QtWidgets.QCheckBox(self.groupBox)
        self.legned.setGeometry(QtCore.QRect(10, 410, 73, 16))
        self.legned.setChecked(True)
        self.legned.setAutoExclusive(False)
        self.legned.setTristate(False)
        self.legned.setObjectName("legned")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.f1 = MW_UQE(self.centralwidget)
        self.f1.setMinimumSize(QtCore.QSize(502, 400))
        self.f1.setObjectName("f1")
        self.verticalLayout.addWidget(self.f1)
        self.hsb_f1 = QtWidgets.QScrollBar(self.centralwidget)
        self.hsb_f1.setMaximum(50)
        self.hsb_f1.setSingleStep(1)
        self.hsb_f1.setPageStep(1)
        self.hsb_f1.setProperty("value", 25)
        self.hsb_f1.setOrientation(QtCore.Qt.Horizontal)
        self.hsb_f1.setObjectName("hsb_f1")
        self.verticalLayout.addWidget(self.hsb_f1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.lines.setSortingEnabled(False)
        self.label.setText(_translate("MainWindow", "ax**2 + bx**1 +c"))
        self.label_2.setText(_translate("MainWindow", "a:"))
        self.label_3.setText(_translate("MainWindow", "b:"))
        self.label_4.setText(_translate("MainWindow", "c:"))
        self.btn_add.setText(_translate("MainWindow", "add"))
        self.btn_del.setText(_translate("MainWindow", "del"))
        self.legned.setText(_translate("MainWindow", "Legend"))

from MatplotlibWidget import MW_UQE
